DROP TABLE TB_APARTAMENTO
DROP TABLE TB_CLIENTE
DROP TABLE TB_CONDOMINIO
DROP TABLE TB_CONSUMO_AGUA
DROP TABLE TB_EMPRESA
DROP TABLE TB_ENDERECO
DROP TABLE TB_FUNCIONARIO
DROP TABLE LOG
DROP TABLE TB_SINDICO
DROP TABLE TB_TORRE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
